---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-12.04
  run_list:
  - recipe[apt::default]
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
    customize:
      cpus: 2
      memory: 1024
- name: centos-6.4
  run_list:
  - recipe[yum::epel]
  driver_config:
    box: opscode-centos-6.4
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box
    customize:
      cpus: 2
      memory: 1024

suites:
- name: server
  run_list:
  - recipe[rs-mysql::server]
  attributes:
    mysql:
      server_root_password: rootpass
      server_debian_password: debpass
      server_repl_password: replpass
- name: client
  run_list:
  - recipe[rs-mysql::client]
- name: database_mysql
  run_list:
  - recipe[rs-mysql::server]
  - recipe[fake::database_mysql]
  attributes:
    mysql:
      server_root_password: rootpass
      server_debian_password: debpass
      server_repl_password: replpass
